name: Fetch Camera Snapshots from LC-Cameras

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Allows write access to the repository contents

jobs:
  fetch_snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the LC-Cameras-Public repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.name "jmorr17"
          git config --local user.email "jmorris@lakecountyco.gov"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests library for API calls

      - name: Fetch and save snapshots from LC-Cameras
        run: |
          git clone https://$GITHUB_TOKEN@github.com/jmorr17/LC-Cameras.git  # Clone the LC-Cameras repo with authentication
          cp -r LC-Cameras/snapshots/* snapshots/  # Copy the 'snapshots' folder from LC-Cameras to LC-Cameras-Public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

      - name: Commit and push new snapshots to LC-Cameras-Public
        run: |
          git remote set-url origin https://$GITHUB_TOKEN@github.com/jmorr17/LC-Cameras-Public.git
          git add snapshots/
          git commit -m "Update camera snapshots from LC-Cameras" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure to use the correct token for authentication
